

package me.TechsCode.EnderPermissions.base.visual;

public class Colors
{
    public static HexColor AliceBlue;
    public static HexColor AntiqueWhite;
    public static HexColor Aqua;
    public static HexColor Aquamarine;
    public static HexColor Azure;
    public static HexColor Beige;
    public static HexColor Bisque;
    public static HexColor Black;
    public static HexColor BlanchedAlmond;
    public static HexColor Blue;
    public static HexColor BlueViolet;
    public static HexColor Brown;
    public static HexColor BurlyWood;
    public static HexColor CadetBlue;
    public static HexColor Chartreuse;
    public static HexColor Chocolate;
    public static HexColor Coral;
    public static HexColor CornflowerBlue;
    public static HexColor Cornsilk;
    public static HexColor Crimson;
    public static HexColor Cyan;
    public static HexColor DarkBlue;
    public static HexColor DarkCyan;
    public static HexColor DarkGoldenRod;
    public static HexColor DarkGray;
    public static HexColor DarkGrey;
    public static HexColor DarkGreen;
    public static HexColor DarkKhaki;
    public static HexColor DarkMagenta;
    public static HexColor DarkOliveGreen;
    public static HexColor Darkorange;
    public static HexColor DarkOrchid;
    public static HexColor DarkRed;
    public static HexColor DarkSalmon;
    public static HexColor DarkSeaGreen;
    public static HexColor DarkSlateBlue;
    public static HexColor DarkSlateGray;
    public static HexColor DarkSlateGrey;
    public static HexColor DarkTurquoise;
    public static HexColor DarkViolet;
    public static HexColor DeepPink;
    public static HexColor DeepSkyBlue;
    public static HexColor DimGray;
    public static HexColor DimGrey;
    public static HexColor DodgerBlue;
    public static HexColor FireBrick;
    public static HexColor FloralWhite;
    public static HexColor ForestGreen;
    public static HexColor Fuchsia;
    public static HexColor Gainsboro;
    public static HexColor GhostWhite;
    public static HexColor Gold;
    public static HexColor GoldenRod;
    public static HexColor Gray;
    public static HexColor Grey;
    public static HexColor Green;
    public static HexColor GreenYellow;
    public static HexColor HoneyDew;
    public static HexColor HotPink;
    public static HexColor IndianRed;
    public static HexColor Indigo;
    public static HexColor Ivory;
    public static HexColor Khaki;
    public static HexColor Lavender;
    public static HexColor LavenderBlush;
    public static HexColor LawnGreen;
    public static HexColor LemonChiffon;
    public static HexColor LightBlue;
    public static HexColor LightCoral;
    public static HexColor LightCyan;
    public static HexColor LightGoldenRodYellow;
    public static HexColor LightGray;
    public static HexColor LightGrey;
    public static HexColor LightGreen;
    public static HexColor LightPink;
    public static HexColor LightSalmon;
    public static HexColor LightSeaGreen;
    public static HexColor LightSkyBlue;
    public static HexColor LightSlateGray;
    public static HexColor LightSlateGrey;
    public static HexColor LightSteelBlue;
    public static HexColor LightYellow;
    public static HexColor Lime;
    public static HexColor LimeGreen;
    public static HexColor Linen;
    public static HexColor Magenta;
    public static HexColor Maroon;
    public static HexColor MediumAquaMarine;
    public static HexColor MediumBlue;
    public static HexColor MediumOrchid;
    public static HexColor MediumPurple;
    public static HexColor MediumSeaGreen;
    public static HexColor MediumSlateBlue;
    public static HexColor MediumSpringGreen;
    public static HexColor MediumTurquoise;
    public static HexColor MediumVioletRed;
    public static HexColor MidnightBlue;
    public static HexColor MintCream;
    public static HexColor MistyRose;
    public static HexColor Moccasin;
    public static HexColor NavajoWhite;
    public static HexColor Navy;
    public static HexColor OldLace;
    public static HexColor Olive;
    public static HexColor OliveDrab;
    public static HexColor Orange;
    public static HexColor OrangeRed;
    public static HexColor Orchid;
    public static HexColor PaleGoldenRod;
    public static HexColor PaleGreen;
    public static HexColor PaleTurquoise;
    public static HexColor PaleVioletRed;
    public static HexColor PapayaWhip;
    public static HexColor PeachPuff;
    public static HexColor Peru;
    public static HexColor Pink;
    public static HexColor Plum;
    public static HexColor PowderBlue;
    public static HexColor Purple;
    public static HexColor Red;
    public static HexColor RosyBrown;
    public static HexColor RoyalBlue;
    public static HexColor SaddleBrown;
    public static HexColor Salmon;
    public static HexColor SandyBrown;
    public static HexColor SeaGreen;
    public static HexColor SeaShell;
    public static HexColor Sienna;
    public static HexColor Silver;
    public static HexColor SkyBlue;
    public static HexColor SlateBlue;
    public static HexColor SlateGray;
    public static HexColor SlateGrey;
    public static HexColor Snow;
    public static HexColor SpringGreen;
    public static HexColor SteelBlue;
    public static HexColor Tan;
    public static HexColor Teal;
    public static HexColor Thistle;
    public static HexColor Tomato;
    public static HexColor Turquoise;
    public static HexColor Violet;
    public static HexColor Wheat;
    public static HexColor White;
    public static HexColor WhiteSmoke;
    public static HexColor Yellow;
    public static HexColor YellowGreen;
    
    static {
        Colors.AliceBlue = HexColor.from("#F0F8FF");
        Colors.AntiqueWhite = HexColor.from("FAEBD7");
        Colors.Aqua = HexColor.from("#00FFFF");
        Colors.Aquamarine = HexColor.from("#7FFFD4");
        Colors.Azure = HexColor.from("#F0FFFF");
        Colors.Beige = HexColor.from("#F5F5DC");
        Colors.Bisque = HexColor.from("#FFE4C4");
        Colors.Black = HexColor.from("#000000");
        Colors.BlanchedAlmond = HexColor.from("#FFEBCD");
        Colors.Blue = HexColor.from("#0000FF");
        Colors.BlueViolet = HexColor.from("#8A2BE2");
        Colors.Brown = HexColor.from("#A52A2A");
        Colors.BurlyWood = HexColor.from("#DEB887");
        Colors.CadetBlue = HexColor.from("#5F9EA0");
        Colors.Chartreuse = HexColor.from("#7FFF00");
        Colors.Chocolate = HexColor.from("#D2691E");
        Colors.Coral = HexColor.from("#FF7F50");
        Colors.CornflowerBlue = HexColor.from("#6495ED");
        Colors.Cornsilk = HexColor.from("#FFF8DC");
        Colors.Crimson = HexColor.from("#DC143C");
        Colors.Cyan = HexColor.from("#00FFFF");
        Colors.DarkBlue = HexColor.from("#00008B");
        Colors.DarkCyan = HexColor.from("#008B8B");
        Colors.DarkGoldenRod = HexColor.from("#B8860B");
        Colors.DarkGray = HexColor.from("#A9A9A9");
        Colors.DarkGrey = HexColor.from("#A9A9A9");
        Colors.DarkGreen = HexColor.from("#006400");
        Colors.DarkKhaki = HexColor.from("#BDB76B");
        Colors.DarkMagenta = HexColor.from("#8B008B");
        Colors.DarkOliveGreen = HexColor.from("#556B2F");
        Colors.Darkorange = HexColor.from("#FF8C00");
        Colors.DarkOrchid = HexColor.from("#9932CC");
        Colors.DarkRed = HexColor.from("#8B0000");
        Colors.DarkSalmon = HexColor.from("#E9967A");
        Colors.DarkSeaGreen = HexColor.from("#8FBC8F");
        Colors.DarkSlateBlue = HexColor.from("#483D8B");
        Colors.DarkSlateGray = HexColor.from("#2F4F4F");
        Colors.DarkSlateGrey = HexColor.from("#2F4F4F");
        Colors.DarkTurquoise = HexColor.from("#00CED1");
        Colors.DarkViolet = HexColor.from("#9400D3");
        Colors.DeepPink = HexColor.from("#FF1493");
        Colors.DeepSkyBlue = HexColor.from("#00BFFF");
        Colors.DimGray = HexColor.from("#696969");
        Colors.DimGrey = HexColor.from("#696969");
        Colors.DodgerBlue = HexColor.from("#1E90FF");
        Colors.FireBrick = HexColor.from("#B22222");
        Colors.FloralWhite = HexColor.from("#FFFAF0");
        Colors.ForestGreen = HexColor.from("#228B22");
        Colors.Fuchsia = HexColor.from("#FF00FF");
        Colors.Gainsboro = HexColor.from("#DCDCDC");
        Colors.GhostWhite = HexColor.from("#F8F8FF");
        Colors.Gold = HexColor.from("#FFD700");
        Colors.GoldenRod = HexColor.from("#DAA520");
        Colors.Gray = HexColor.from("#808080");
        Colors.Grey = HexColor.from("#808080");
        Colors.Green = HexColor.from("#008000");
        Colors.GreenYellow = HexColor.from("#ADFF2F");
        Colors.HoneyDew = HexColor.from("#F0FFF0");
        Colors.HotPink = HexColor.from("#FF69B4");
        Colors.IndianRed = HexColor.from("#CD5C5C");
        Colors.Indigo = HexColor.from("#4B0082");
        Colors.Ivory = HexColor.from("#FFFFF0");
        Colors.Khaki = HexColor.from("#F0E68C");
        Colors.Lavender = HexColor.from("#E6E6FA");
        Colors.LavenderBlush = HexColor.from("#FFF0F5");
        Colors.LawnGreen = HexColor.from("#7CFC00");
        Colors.LemonChiffon = HexColor.from("#FFFACD");
        Colors.LightBlue = HexColor.from("#ADD8E6");
        Colors.LightCoral = HexColor.from("#F08080");
        Colors.LightCyan = HexColor.from("#E0FFFF");
        Colors.LightGoldenRodYellow = HexColor.from("#FAFAD2");
        Colors.LightGray = HexColor.from("#D3D3D3");
        Colors.LightGrey = HexColor.from("#D3D3D3");
        Colors.LightGreen = HexColor.from("#90EE90");
        Colors.LightPink = HexColor.from("#FFB6C1");
        Colors.LightSalmon = HexColor.from("#FFA07A");
        Colors.LightSeaGreen = HexColor.from("#20B2AA");
        Colors.LightSkyBlue = HexColor.from("#87CEFA");
        Colors.LightSlateGray = HexColor.from("#778899");
        Colors.LightSlateGrey = HexColor.from("#778899");
        Colors.LightSteelBlue = HexColor.from("#B0C4DE");
        Colors.LightYellow = HexColor.from("#FFFFE0");
        Colors.Lime = HexColor.from("#00FF00");
        Colors.LimeGreen = HexColor.from("#32CD32");
        Colors.Linen = HexColor.from("#FAF0E6");
        Colors.Magenta = HexColor.from("#FF00FF");
        Colors.Maroon = HexColor.from("#800000");
        Colors.MediumAquaMarine = HexColor.from("#66CDAA");
        Colors.MediumBlue = HexColor.from("#0000CD");
        Colors.MediumOrchid = HexColor.from("#BA55D3");
        Colors.MediumPurple = HexColor.from("#9370D8");
        Colors.MediumSeaGreen = HexColor.from("#3CB371");
        Colors.MediumSlateBlue = HexColor.from("#7B68EE");
        Colors.MediumSpringGreen = HexColor.from("#00FA9A");
        Colors.MediumTurquoise = HexColor.from("#48D1CC");
        Colors.MediumVioletRed = HexColor.from("#C71585");
        Colors.MidnightBlue = HexColor.from("#191970");
        Colors.MintCream = HexColor.from("#F5FFFA");
        Colors.MistyRose = HexColor.from("#FFE4E1");
        Colors.Moccasin = HexColor.from("#FFE4B5");
        Colors.NavajoWhite = HexColor.from("#FFDEAD");
        Colors.Navy = HexColor.from("#000080");
        Colors.OldLace = HexColor.from("#FDF5E6");
        Colors.Olive = HexColor.from("#808000");
        Colors.OliveDrab = HexColor.from("#6B8E23");
        Colors.Orange = HexColor.from("#FFA500");
        Colors.OrangeRed = HexColor.from("#FF4500");
        Colors.Orchid = HexColor.from("#DA70D6");
        Colors.PaleGoldenRod = HexColor.from("#EEE8AA");
        Colors.PaleGreen = HexColor.from("#98FB98");
        Colors.PaleTurquoise = HexColor.from("#AFEEEE");
        Colors.PaleVioletRed = HexColor.from("#D87093");
        Colors.PapayaWhip = HexColor.from("#FFEFD5");
        Colors.PeachPuff = HexColor.from("#FFDAB9");
        Colors.Peru = HexColor.from("#CD853F");
        Colors.Pink = HexColor.from("#FFC0CB");
        Colors.Plum = HexColor.from("#DDA0DD");
        Colors.PowderBlue = HexColor.from("#B0E0E6");
        Colors.Purple = HexColor.from("#800080");
        Colors.Red = HexColor.from("#FF0000");
        Colors.RosyBrown = HexColor.from("#BC8F8F");
        Colors.RoyalBlue = HexColor.from("#4169E1");
        Colors.SaddleBrown = HexColor.from("#8B4513");
        Colors.Salmon = HexColor.from("#FA8072");
        Colors.SandyBrown = HexColor.from("#F4A460");
        Colors.SeaGreen = HexColor.from("#2E8B57");
        Colors.SeaShell = HexColor.from("#FFF5EE");
        Colors.Sienna = HexColor.from("#A0522D");
        Colors.Silver = HexColor.from("#C0C0C0");
        Colors.SkyBlue = HexColor.from("#87CEEB");
        Colors.SlateBlue = HexColor.from("#6A5ACD");
        Colors.SlateGray = HexColor.from("#708090");
        Colors.SlateGrey = HexColor.from("#708090");
        Colors.Snow = HexColor.from("#FFFAFA");
        Colors.SpringGreen = HexColor.from("#00FF7F");
        Colors.SteelBlue = HexColor.from("#4682B4");
        Colors.Tan = HexColor.from("#D2B48C");
        Colors.Teal = HexColor.from("#008080");
        Colors.Thistle = HexColor.from("#D8BFD8");
        Colors.Tomato = HexColor.from("#FF6347");
        Colors.Turquoise = HexColor.from("#40E0D0");
        Colors.Violet = HexColor.from("#EE82EE");
        Colors.Wheat = HexColor.from("#F5DEB3");
        Colors.White = HexColor.from("#FFFFFF");
        Colors.WhiteSmoke = HexColor.from("#F5F5F5");
        Colors.Yellow = HexColor.from("#FFFF00");
        Colors.YellowGreen = HexColor.from("#9ACD32");
    }
}
